version: '3.3'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8002:8000
    env_file:
      - ./backend/dev.env
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/backend
