# Generated by Django 4.0 on 2023-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabletodo',
            options={},
        ),
        migrations.AlterField(
            model_name='tabletodo',
            name='created_on',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='tabletodo',
            name='task_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('on_going', 'Ongoing'), ('not_started', 'Not Started')], default='not_started', max_length=50),
        ),
    ]
