# Generated by Django 4.0 on 2023-07-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tabletodo_options_alter_tabletodo_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletodo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
